[project]
name = "Next-Gen App Development"
version = "1.0.0"
description = "A project aimed at developing a next-generation application with cutting-edge technology."
author = "Development Team"

[milestones]

[milestones.design]
name = "UI/UX Design Phase"
deadline = "2025-01-15"
description = "Complete all user interface and experience design aspects."
[milestones.design.tasks]
[milestones.design.tasks.task1]
name = "Create wireframes for main screens"
tags = ["wireframes", "UI"]
finish = "2024-11-28"  # Task completed on this date
by = "ana"

[milestones.design.tasks.task2]
name = "Design color palette and typography"
tags = ["design", "visuals"]
finish = ""  # Not yet finished
by = ""

[milestones.design.tasks.task3]
name = "Gather user feedback on prototypes"
tags = ["feedback", "prototype"]
finish = ""  # In progress, no completion date yet
by = ""

[milestones.programming]
name = "Backend Development"
deadline = "2025-02-15"
description = "Develop a robust backend for the application."
[milestones.programming.tasks]
[milestones.programming.tasks.task1]
name = "Set up initial project architecture"
tags = ["backend", "architecture"]
finish = "2024-11-25"
by = "john"

[milestones.programming.tasks.task2]
name = "Implement authentication system"
tags = ["auth", "security"]
finish = ""
by = ""

[milestones.programming.tasks.task3]
name = "Connect database with API"
tags = ["database", "API"]
finish = ""
by = ""

[milestones.testing]
name = "Quality Assurance"
deadline = "2025-03-01"
description = "Test all features to ensure a bug-free release."
[milestones.testing.tasks]
[milestones.testing.tasks.task1]
name = "Write unit tests for critical modules"
tags = ["testing", "unit-tests"]
finish = ""
by = ""

[milestones.testing.tasks.task2]
name = "Conduct usability testing"
tags = ["usability", "testing"]
finish = ""
by = ""

[members]
[members.john]
name = "John Doe"
role = "Backend Engineer"
email = "john.doe@gmail.com"

[members.ana]
name = "Ana Smith"
role = "UI/UX Designer"
email = "ana.smith@gmail.com"

[members.jane]
name = "Jane Wilson"
role = "Full Stack Developer"
email = "jane.wilson@gmail.com"

[members.lisa]
name = "Lisa Brown"
role = "QA Specialist"
email = "lisa.brown@gmail.com"
