[[test]]
id = "TST-001"
requirement_id = "RQ-F001"
description = "Test description: What does the test do?"
expected = "Some value to be expected"
result = "Result"
status = "pending" # approved or rejected
evidence = ["assets/test/___.png"]

[[test]]
id = "TST-002"
requirement_id = "RQ-NF001"
description = "Test description: What does the test do?"
expected = "Some value to be expected"
result = "Result"
status = "pending" # approved or rejected
evidence = ["assets/test/___.png"]
